import spriteTable from "./spriteTable";

const textureDefs: {
  block: string;
  textures: string | string[];
}[] = [
  {
    block: "unknown",
    textures: "unknown",
  },
  {
    block: "minecraft:sand",
    textures: "sand",
  },
  {
    block: "minecraft:cactus",
    textures: [
      "cactus_side",
      "cactus_side",
      "cactus_top",
      "cactus_bottom",
      "cactus_side",
      "cactus_side",
    ],
  },
  {
    block: "minecraft:sandstone",
    textures: [
      "sandstone",
      "sandstone",
      "sandstone_top",
      "sandstone_bottom",
      "sandstone",
      "sandstone",
    ],
  },
  {
    block: "minecraft:dirt",
    textures: "dirt",
  },
  {
    block: "minecraft:stone",
    textures: "stone",
  },
];

export const getBlockTypes = () => {
  const textureSet = new Set<string>();
  for (const { textures } of textureDefs) {
    const isArray = textures instanceof Array;
    if (isArray) {
      textures.forEach((texture) => textureSet.add(texture));
    } else {
      textureSet.add(textures);
    }
  }

  const textures = Array.from(textureSet);
  const textureMap = new Map<string, number[]>();
  for (const { block, textures: texturesFromDef } of textureDefs) {
    const isArray = texturesFromDef instanceof Array;
    if (isArray) {
      const textureIndexArray = [0, 0, 0, 0, 0, 0];
      for (let i = 0; i < 6; i++) {
        textureIndexArray[i] = textures.indexOf(texturesFromDef[i]);
      }
      textureMap.set(block, textureIndexArray);
    } else {
      const index = textures.indexOf(texturesFromDef);
      textureMap.set(block, [index, index, index, index, index, index]);
    }
  }

  return {
    textures,
    textureMap,
  };
};

export const blockNameOverride = (blockName: string) => {
  switch (blockName) {
    case "minecraft:wheat":
      return "minecraft:wheat_stage7";
    case "minecraft:cocoa":
      return "minecraft:cocoa_stage2";
    case "minecraft:beetroots":
      return "minecraft:beetroots_stage3";
    case "minecraft:carrots":
      return "minecraft:carrots_stage3";
    case "minecraft:melon_stem":
      return "minecraft:melon_stem_stage6";
    case "minecraft:pumpkin_stem":
      return "minecraft:pumpkin_stem_stage6";
    case "minecraft:nether_wart":
      return "minecraft:nether_wart_stage2";
    case "minecraft:potatoes":
      return "minecraft:potatoes_stage3";
    case "minecraft:sweet_berry_bush":
      return "minecraft:sweet_berry_bush_stage3";
    case "minecraft:torchflower_crop":
      return "minecraft:torchflower_crop_stage1";
    case "minecraft:bamboo":
      return "minecraft:bamboo4_age1";
    case "minecraft:snow":
      return "minecraft:snow_height2";
    case "minecraft:tall_grass":
      return "minecraft:tall_grass_bottom";
    case "minecraft:tall_seagrass":
      return "minecraft:tall_seagrass_bottom";
    case "computercraft:wireless_modem_normal":
      return "computercraft:wireless_modem_normal_on";
    case "computercraft:wired_modem":
      return "computercraft:wired_modem_on";
    case "computercraft:computer_normal":
      return "computercraft:computer_normal_on";
    case "computercraft:disk_drive":
      return "computercraft:disk_drive_full";
    case "computercraft:printer":
      return "computercraft:printer_both_full";
    case "computercraft:wired_modem_full":
      return "computercraft:wired_modem_full_off";
    default:
      return blockName;
  }
};

export const BlockNames: string[] = Object.keys(spriteTable).slice(2);

export const grabcraftNameToBlockMap: {
  [key: string]: string;
} = {
  "Acacia Button": "minecraft:acacia_button",
  "Acacia Door": "minecraft:acacia_door",
  "Acacia Fence": "minecraft:acacia_fence",
  "Acacia Fence Gate": "minecraft:acacia_fence_gate",
  "Acacia Hanging Sign": "minecraft:acacia_hanging_sign",
  "Acacia Leaves": "minecraft:acacia_leaves",
  "Acacia Log": "minecraft:acacia_log",
  "Acacia Planks": "minecraft:acacia_planks",
  "Acacia Pressure Plate": "minecraft:acacia_pressure_plate",
  "Acacia Sapling": "minecraft:acacia_sapling",
  "Acacia Sign": "minecraft:acacia_sign",
  "Acacia Slab": "minecraft:acacia_slab",
  "Acacia Stairs": "minecraft:acacia_stairs",
  "Acacia Trapdoor": "minecraft:acacia_trapdoor",
  "Acacia Wall Hanging Sign": "minecraft:acacia_wall_hanging_sign",
  "Acacia Wall Sign": "minecraft:acacia_wall_sign",
  "Acacia Wood": "minecraft:acacia_wood",
  "Activator Rail": "minecraft:activator_rail",
  Air: "minecraft:air",
  Allium: "minecraft:allium",
  "Block of Amethyst": "minecraft:amethyst_block",
  "Amethyst Cluster": "minecraft:amethyst_cluster",
  "Ancient Debris": "minecraft:ancient_debris",
  Andesite: "minecraft:andesite",
  "Andesite Slab": "minecraft:andesite_slab",
  "Andesite Stairs": "minecraft:andesite_stairs",
  "Andesite Wall": "minecraft:andesite_wall",
  Anvil: "minecraft:anvil",
  "Attached Melon Stem": "minecraft:attached_melon_stem",
  "Attached Pumpkin Stem": "minecraft:attached_pumpkin_stem",
  Azalea: "minecraft:azalea",
  "Azalea Leaves": "minecraft:azalea_leaves",
  "Azure Bluet": "minecraft:azure_bluet",
  Bamboo: "minecraft:bamboo",
  "Block of Bamboo": "minecraft:bamboo_block",
  "Bamboo Button": "minecraft:bamboo_button",
  "Bamboo Door": "minecraft:bamboo_door",
  "Bamboo Fence": "minecraft:bamboo_fence",
  "Bamboo Fence Gate": "minecraft:bamboo_fence_gate",
  "Bamboo Hanging Sign": "minecraft:bamboo_hanging_sign",
  "Bamboo Mosaic": "minecraft:bamboo_mosaic",
  "Bamboo Mosaic Slab": "minecraft:bamboo_mosaic_slab",
  "Bamboo Mosaic Stairs": "minecraft:bamboo_mosaic_stairs",
  "Bamboo Planks": "minecraft:bamboo_planks",
  "Bamboo Pressure Plate": "minecraft:bamboo_pressure_plate",
  "Bamboo Shoot": "minecraft:bamboo_sapling",
  "Bamboo Sign": "minecraft:bamboo_sign",
  "Bamboo Slab": "minecraft:bamboo_slab",
  "Bamboo Stairs": "minecraft:bamboo_stairs",
  "Bamboo Trapdoor": "minecraft:bamboo_trapdoor",
  "Bamboo Wall Hanging Sign": "minecraft:bamboo_wall_hanging_sign",
  "Bamboo Wall Sign": "minecraft:bamboo_wall_sign",
  Barrel: "minecraft:barrel",
  Barrier: "minecraft:barrier",
  Basalt: "minecraft:basalt",
  Beacon: "minecraft:beacon",
  Bedrock: "minecraft:bedrock",
  "Bee Nest": "minecraft:bee_nest",
  Beehive: "minecraft:beehive",
  Beetroots: "minecraft:beetroots",
  Bell: "minecraft:bell",
  "Big Dripleaf": "minecraft:big_dripleaf",
  "Big Dripleaf Stem": "minecraft:big_dripleaf_stem",
  "Birch Button": "minecraft:birch_button",
  "Birch Door": "minecraft:birch_door",
  "Birch Fence": "minecraft:birch_fence",
  "Birch Fence Gate": "minecraft:birch_fence_gate",
  "Birch Hanging Sign": "minecraft:birch_hanging_sign",
  "Birch Leaves": "minecraft:birch_leaves",
  "Birch Log": "minecraft:birch_log",
  "Birch Planks": "minecraft:birch_planks",
  "Birch Pressure Plate": "minecraft:birch_pressure_plate",
  "Birch Sapling": "minecraft:birch_sapling",
  "Birch Sign": "minecraft:birch_sign",
  "Birch Slab": "minecraft:birch_slab",
  "Birch Stairs": "minecraft:birch_stairs",
  "Birch Trapdoor": "minecraft:birch_trapdoor",
  "Birch Wall Hanging Sign": "minecraft:birch_wall_hanging_sign",
  "Birch Wall Sign": "minecraft:birch_wall_sign",
  "Birch Wood": "minecraft:birch_wood",
  "Black Banner": "minecraft:black_banner",
  "Black Bed": "minecraft:black_bed",
  "Black Candle": "minecraft:black_candle",
  "Cake with Black Candle": "minecraft:black_candle_cake",
  "Black Carpet": "minecraft:black_carpet",
  "Black Concrete": "minecraft:black_concrete",
  "Black Concrete Powder": "minecraft:black_concrete_powder",
  "Black Glazed Terracotta": "minecraft:black_glazed_terracotta",
  "Black Shulker Box": "minecraft:black_shulker_box",
  "Black Stained Glass": "minecraft:black_stained_glass",
  "Black Stained Glass Pane": "minecraft:black_stained_glass_pane",
  "Black Terracotta": "minecraft:black_terracotta",
  "Black Wool": "minecraft:black_wool",
  Blackstone: "minecraft:blackstone",
  "Blackstone Slab": "minecraft:blackstone_slab",
  "Blackstone Stairs": "minecraft:blackstone_stairs",
  "Blackstone Wall": "minecraft:blackstone_wall",
  "Blast Furnace": "minecraft:blast_furnace",
  "Blue Banner": "minecraft:blue_banner",
  "Blue Bed": "minecraft:blue_bed",
  "Blue Candle": "minecraft:blue_candle",
  "Cake with Blue Candle": "minecraft:blue_candle_cake",
  "Blue Carpet": "minecraft:blue_carpet",
  "Blue Concrete": "minecraft:blue_concrete",
  "Blue Concrete Powder": "minecraft:blue_concrete_powder",
  "Blue Glazed Terracotta": "minecraft:blue_glazed_terracotta",
  "Blue Ice": "minecraft:blue_ice",
  "Blue Orchid": "minecraft:blue_orchid",
  "Blue Shulker Box": "minecraft:blue_shulker_box",
  "Blue Stained Glass": "minecraft:blue_stained_glass",
  "Blue Stained Glass Pane": "minecraft:blue_stained_glass_pane",
  "Blue Terracotta": "minecraft:blue_terracotta",
  "Blue Wool": "minecraft:blue_wool",
  "Bone Block": "minecraft:bone_block",
  Bookshelf: "minecraft:bookshelf",
  "Brain Coral": "minecraft:brain_coral",
  "Brain Coral Block": "minecraft:brain_coral_block",
  "Brain Coral Fan": "minecraft:brain_coral_fan",
  "Brain Coral Wall Fan": "minecraft:brain_coral_wall_fan",
  "Brewing Stand": "minecraft:brewing_stand",
  "Brick Slab": "minecraft:brick_slab",
  "Brick Stairs": "minecraft:brick_stairs",
  "Brick Wall": "minecraft:brick_wall",
  Bricks: "minecraft:bricks",
  "Brown Banner": "minecraft:brown_banner",
  "Brown Bed": "minecraft:brown_bed",
  "Brown Candle": "minecraft:brown_candle",
  "Cake with Brown Candle": "minecraft:brown_candle_cake",
  "Brown Carpet": "minecraft:brown_carpet",
  "Brown Concrete": "minecraft:brown_concrete",
  "Brown Concrete Powder": "minecraft:brown_concrete_powder",
  "Brown Glazed Terracotta": "minecraft:brown_glazed_terracotta",
  "Brown Mushroom": "minecraft:brown_mushroom",
  "Brown Mushroom Block": "minecraft:brown_mushroom_block",
  "Brown Shulker Box": "minecraft:brown_shulker_box",
  "Brown Stained Glass": "minecraft:brown_stained_glass",
  "Brown Stained Glass Pane": "minecraft:brown_stained_glass_pane",
  "Brown Terracotta": "minecraft:brown_terracotta",
  "Brown Wool": "minecraft:brown_wool",
  "Bubble Column": "minecraft:bubble_column",
  "Bubble Coral": "minecraft:bubble_coral",
  "Bubble Coral Block": "minecraft:bubble_coral_block",
  "Bubble Coral Fan": "minecraft:bubble_coral_fan",
  "Bubble Coral Wall Fan": "minecraft:bubble_coral_wall_fan",
  "Budding Amethyst": "minecraft:budding_amethyst",
  Cactus: "minecraft:cactus",
  Cake: "minecraft:cake",
  Calcite: "minecraft:calcite",
  "Calibrated Sculk Sensor": "minecraft:calibrated_sculk_sensor",
  Campfire: "minecraft:campfire",
  Candle: "minecraft:candle",
  "Cake with Candle": "minecraft:candle_cake",
  Carrots: "minecraft:carrots",
  "Cartography Table": "minecraft:cartography_table",
  "Carved Pumpkin": "minecraft:carved_pumpkin",
  Cauldron: "minecraft:cauldron",
  "Cave Air": "minecraft:cave_air",
  "Cave Vines": "minecraft:cave_vines",
  "Cave Vines Plant": "minecraft:cave_vines_plant",
  Chain: "minecraft:chain",
  "Chain Command Block": "minecraft:chain_command_block",
  "Cherry Button": "minecraft:cherry_button",
  "Cherry Door": "minecraft:cherry_door",
  "Cherry Fence": "minecraft:cherry_fence",
  "Cherry Fence Gate": "minecraft:cherry_fence_gate",
  "Cherry Hanging Sign": "minecraft:cherry_hanging_sign",
  "Cherry Leaves": "minecraft:cherry_leaves",
  "Cherry Log": "minecraft:cherry_log",
  "Cherry Planks": "minecraft:cherry_planks",
  "Cherry Pressure Plate": "minecraft:cherry_pressure_plate",
  "Cherry Sapling": "minecraft:cherry_sapling",
  "Cherry Sign": "minecraft:cherry_sign",
  "Cherry Slab": "minecraft:cherry_slab",
  "Cherry Stairs": "minecraft:cherry_stairs",
  "Cherry Trapdoor": "minecraft:cherry_trapdoor",
  "Cherry Wall Hanging Sign": "minecraft:cherry_wall_hanging_sign",
  "Cherry Wall Sign": "minecraft:cherry_wall_sign",
  "Cherry Wood": "minecraft:cherry_wood",
  Chest: "minecraft:chest",
  "Chipped Anvil": "minecraft:chipped_anvil",
  "Chiseled Bookshelf": "minecraft:chiseled_bookshelf",
  "Chiseled Deepslate": "minecraft:chiseled_deepslate",
  "Chiseled Nether Bricks": "minecraft:chiseled_nether_bricks",
  "Chiseled Polished Blackstone": "minecraft:chiseled_polished_blackstone",
  "Chiseled Quartz Block": "minecraft:chiseled_quartz_block",
  "Chiseled Red Sandstone": "minecraft:chiseled_red_sandstone",
  "Chiseled Sandstone": "minecraft:chiseled_sandstone",
  "Chiseled Stone Bricks": "minecraft:chiseled_stone_bricks",
  "Chorus Flower": "minecraft:chorus_flower",
  "Chorus Plant": "minecraft:chorus_plant",
  Clay: "minecraft:clay",
  "Block of Coal": "minecraft:coal_block",
  "Coal Ore": "minecraft:coal_ore",
  "Coarse Dirt": "minecraft:coarse_dirt",
  "Cobbled Deepslate": "minecraft:cobbled_deepslate",
  "Cobbled Deepslate Slab": "minecraft:cobbled_deepslate_slab",
  "Cobbled Deepslate Stairs": "minecraft:cobbled_deepslate_stairs",
  "Cobbled Deepslate Wall": "minecraft:cobbled_deepslate_wall",
  Cobblestone: "minecraft:cobblestone",
  "Cobblestone Slab": "minecraft:cobblestone_slab",
  "Cobblestone Stairs": "minecraft:cobblestone_stairs",
  "Cobblestone Wall": "minecraft:cobblestone_wall",
  Cobweb: "minecraft:cobweb",
  Cocoa: "minecraft:cocoa",
  "Command Block": "minecraft:command_block",
  "Redstone Comparator": "minecraft:comparator",
  Composter: "minecraft:composter",
  Conduit: "minecraft:conduit",
  "Block of Copper": "minecraft:copper_block",
  "Copper Ore": "minecraft:copper_ore",
  Cornflower: "minecraft:cornflower",
  "Cracked Deepslate Bricks": "minecraft:cracked_deepslate_bricks",
  "Cracked Deepslate Tiles": "minecraft:cracked_deepslate_tiles",
  "Cracked Nether Bricks": "minecraft:cracked_nether_bricks",
  "Cracked Polished Blackstone Bricks":
    "minecraft:cracked_polished_blackstone_bricks",
  "Cracked Stone Bricks": "minecraft:cracked_stone_bricks",
  "Crafting Table": "minecraft:crafting_table",
  "Creeper Head": "minecraft:creeper_head",
  "Creeper Wall Head": "minecraft:creeper_wall_head",
  "Crimson Button": "minecraft:crimson_button",
  "Crimson Door": "minecraft:crimson_door",
  "Crimson Fence": "minecraft:crimson_fence",
  "Crimson Fence Gate": "minecraft:crimson_fence_gate",
  "Crimson Fungus": "minecraft:crimson_fungus",
  "Crimson Hanging Sign": "minecraft:crimson_hanging_sign",
  "Crimson Hyphae": "minecraft:crimson_hyphae",
  "Crimson Nylium": "minecraft:crimson_nylium",
  "Crimson Planks": "minecraft:crimson_planks",
  "Crimson Pressure Plate": "minecraft:crimson_pressure_plate",
  "Crimson Roots": "minecraft:crimson_roots",
  "Crimson Sign": "minecraft:crimson_sign",
  "Crimson Slab": "minecraft:crimson_slab",
  "Crimson Stairs": "minecraft:crimson_stairs",
  "Crimson Stem": "minecraft:crimson_stem",
  "Crimson Trapdoor": "minecraft:crimson_trapdoor",
  "Crimson Wall Hanging Sign": "minecraft:crimson_wall_hanging_sign",
  "Crimson Wall Sign": "minecraft:crimson_wall_sign",
  "Crying Obsidian": "minecraft:crying_obsidian",
  "Cut Copper": "minecraft:cut_copper",
  "Cut Copper Slab": "minecraft:cut_copper_slab",
  "Cut Copper Stairs": "minecraft:cut_copper_stairs",
  "Cut Red Sandstone": "minecraft:cut_red_sandstone",
  "Cut Red Sandstone Slab": "minecraft:cut_red_sandstone_slab",
  "Cut Sandstone": "minecraft:cut_sandstone",
  "Cut Sandstone Slab": "minecraft:cut_sandstone_slab",
  "Cyan Banner": "minecraft:cyan_banner",
  "Cyan Bed": "minecraft:cyan_bed",
  "Cyan Candle": "minecraft:cyan_candle",
  "Cake with Cyan Candle": "minecraft:cyan_candle_cake",
  "Cyan Carpet": "minecraft:cyan_carpet",
  "Cyan Concrete": "minecraft:cyan_concrete",
  "Cyan Concrete Powder": "minecraft:cyan_concrete_powder",
  "Cyan Glazed Terracotta": "minecraft:cyan_glazed_terracotta",
  "Cyan Shulker Box": "minecraft:cyan_shulker_box",
  "Cyan Stained Glass": "minecraft:cyan_stained_glass",
  "Cyan Stained Glass Pane": "minecraft:cyan_stained_glass_pane",
  "Cyan Terracotta": "minecraft:cyan_terracotta",
  "Cyan Wool": "minecraft:cyan_wool",
  "Damaged Anvil": "minecraft:damaged_anvil",
  Dandelion: "minecraft:dandelion",
  "Dark Oak Button": "minecraft:dark_oak_button",
  "Dark Oak Door": "minecraft:dark_oak_door",
  "Dark Oak Fence": "minecraft:dark_oak_fence",
  "Dark Oak Fence Gate": "minecraft:dark_oak_fence_gate",
  "Dark Oak Hanging Sign": "minecraft:dark_oak_hanging_sign",
  "Dark Oak Leaves": "minecraft:dark_oak_leaves",
  "Dark Oak Log": "minecraft:dark_oak_log",
  "Dark Oak Planks": "minecraft:dark_oak_planks",
  "Dark Oak Pressure Plate": "minecraft:dark_oak_pressure_plate",
  "Dark Oak Sapling": "minecraft:dark_oak_sapling",
  "Dark Oak Sign": "minecraft:dark_oak_sign",
  "Dark Oak Slab": "minecraft:dark_oak_slab",
  "Dark Oak Stairs": "minecraft:dark_oak_stairs",
  "Dark Oak Trapdoor": "minecraft:dark_oak_trapdoor",
  "Dark Oak Wall Hanging Sign": "minecraft:dark_oak_wall_hanging_sign",
  "Dark Oak Wall Sign": "minecraft:dark_oak_wall_sign",
  "Dark Oak Wood": "minecraft:dark_oak_wood",
  "Dark Prismarine": "minecraft:dark_prismarine",
  "Dark Prismarine Slab": "minecraft:dark_prismarine_slab",
  "Dark Prismarine Stairs": "minecraft:dark_prismarine_stairs",
  "Daylight Detector": "minecraft:daylight_detector",
  "Dead Brain Coral": "minecraft:dead_brain_coral",
  "Dead Brain Coral Block": "minecraft:dead_brain_coral_block",
  "Dead Brain Coral Fan": "minecraft:dead_brain_coral_fan",
  "Dead Brain Coral Wall Fan": "minecraft:dead_brain_coral_wall_fan",
  "Dead Bubble Coral": "minecraft:dead_bubble_coral",
  "Dead Bubble Coral Block": "minecraft:dead_bubble_coral_block",
  "Dead Bubble Coral Fan": "minecraft:dead_bubble_coral_fan",
  "Dead Bubble Coral Wall Fan": "minecraft:dead_bubble_coral_wall_fan",
  "Dead Bush": "minecraft:dead_bush",
  "Dead Fire Coral": "minecraft:dead_fire_coral",
  "Dead Fire Coral Block": "minecraft:dead_fire_coral_block",
  "Dead Fire Coral Fan": "minecraft:dead_fire_coral_fan",
  "Dead Fire Coral Wall Fan": "minecraft:dead_fire_coral_wall_fan",
  "Dead Horn Coral": "minecraft:dead_horn_coral",
  "Dead Horn Coral Block": "minecraft:dead_horn_coral_block",
  "Dead Horn Coral Fan": "minecraft:dead_horn_coral_fan",
  "Dead Horn Coral Wall Fan": "minecraft:dead_horn_coral_wall_fan",
  "Dead Tube Coral": "minecraft:dead_tube_coral",
  "Dead Tube Coral Block": "minecraft:dead_tube_coral_block",
  "Dead Tube Coral Fan": "minecraft:dead_tube_coral_fan",
  "Dead Tube Coral Wall Fan": "minecraft:dead_tube_coral_wall_fan",
  "Decorated Pot": "minecraft:decorated_pot",
  Deepslate: "minecraft:deepslate",
  "Deepslate Brick Slab": "minecraft:deepslate_brick_slab",
  "Deepslate Brick Stairs": "minecraft:deepslate_brick_stairs",
  "Deepslate Brick Wall": "minecraft:deepslate_brick_wall",
  "Deepslate Bricks": "minecraft:deepslate_bricks",
  "Deepslate Coal Ore": "minecraft:deepslate_coal_ore",
  "Deepslate Copper Ore": "minecraft:deepslate_copper_ore",
  "Deepslate Diamond Ore": "minecraft:deepslate_diamond_ore",
  "Deepslate Emerald Ore": "minecraft:deepslate_emerald_ore",
  "Deepslate Gold Ore": "minecraft:deepslate_gold_ore",
  "Deepslate Iron Ore": "minecraft:deepslate_iron_ore",
  "Deepslate Lapis Lazuli Ore": "minecraft:deepslate_lapis_ore",
  "Deepslate Redstone Ore": "minecraft:deepslate_redstone_ore",
  "Deepslate Tile Slab": "minecraft:deepslate_tile_slab",
  "Deepslate Tile Stairs": "minecraft:deepslate_tile_stairs",
  "Deepslate Tile Wall": "minecraft:deepslate_tile_wall",
  "Deepslate Tiles": "minecraft:deepslate_tiles",
  "Detector Rail": "minecraft:detector_rail",
  "Block of Diamond": "minecraft:diamond_block",
  "Diamond Ore": "minecraft:diamond_ore",
  Diorite: "minecraft:diorite",
  "Diorite Slab": "minecraft:diorite_slab",
  "Diorite Stairs": "minecraft:diorite_stairs",
  "Diorite Wall": "minecraft:diorite_wall",
  Dirt: "minecraft:dirt",
  "Dirt Path": "minecraft:dirt_path",
  Dispenser: "minecraft:dispenser",
  "Dragon Egg": "minecraft:dragon_egg",
  "Dragon Head": "minecraft:dragon_head",
  "Dragon Wall Head": "minecraft:dragon_wall_head",
  "Dried Kelp Block": "minecraft:dried_kelp_block",
  "Dripstone Block": "minecraft:dripstone_block",
  Dropper: "minecraft:dropper",
  "Block of Emerald": "minecraft:emerald_block",
  "Emerald Ore": "minecraft:emerald_ore",
  "Enchanting Table": "minecraft:enchanting_table",
  "End Gateway": "minecraft:end_gateway",
  "End Portal": "minecraft:end_portal",
  "End Portal Frame": "minecraft:end_portal_frame",
  "End Rod": "minecraft:end_rod",
  "End Stone": "minecraft:end_stone",
  "End Stone Brick Slab": "minecraft:end_stone_brick_slab",
  "End Stone Brick Stairs": "minecraft:end_stone_brick_stairs",
  "End Stone Brick Wall": "minecraft:end_stone_brick_wall",
  "End Stone Bricks": "minecraft:end_stone_bricks",
  "Ender Chest": "minecraft:ender_chest",
  "Exposed Copper": "minecraft:exposed_copper",
  "Exposed Cut Copper": "minecraft:exposed_cut_copper",
  "Exposed Cut Copper Slab": "minecraft:exposed_cut_copper_slab",
  "Exposed Cut Copper Stairs": "minecraft:exposed_cut_copper_stairs",
  Farmland: "minecraft:farmland",
  Fern: "minecraft:fern",
  Fire: "minecraft:fire",
  "Fire Coral": "minecraft:fire_coral",
  "Fire Coral Block": "minecraft:fire_coral_block",
  "Fire Coral Fan": "minecraft:fire_coral_fan",
  "Fire Coral Wall Fan": "minecraft:fire_coral_wall_fan",
  "Fletching Table": "minecraft:fletching_table",
  "Flower Pot": "minecraft:flower_pot",
  "Flowering Azalea": "minecraft:flowering_azalea",
  "Flowering Azalea Leaves": "minecraft:flowering_azalea_leaves",
  Frogspawn: "minecraft:frogspawn",
  "Frosted Ice": "minecraft:frosted_ice",
  Furnace: "minecraft:furnace",
  "Gilded Blackstone": "minecraft:gilded_blackstone",
  Glass: "minecraft:glass",
  "Glass Pane": "minecraft:glass_pane",
  "Glow Lichen": "minecraft:glow_lichen",
  Glowstone: "minecraft:glowstone",
  "Block of Gold": "minecraft:gold_block",
  "Gold Ore": "minecraft:gold_ore",
  Granite: "minecraft:granite",
  "Granite Slab": "minecraft:granite_slab",
  "Granite Stairs": "minecraft:granite_stairs",
  "Granite Wall": "minecraft:granite_wall",
  Grass: "minecraft:grass",
  "Grass Block": "minecraft:grass_block",
  Gravel: "minecraft:gravel",
  "Gray Banner": "minecraft:gray_banner",
  "Gray Bed": "minecraft:gray_bed",
  "Gray Candle": "minecraft:gray_candle",
  "Cake with Gray Candle": "minecraft:gray_candle_cake",
  "Gray Carpet": "minecraft:gray_carpet",
  "Gray Concrete": "minecraft:gray_concrete",
  "Gray Concrete Powder": "minecraft:gray_concrete_powder",
  "Gray Glazed Terracotta": "minecraft:gray_glazed_terracotta",
  "Gray Shulker Box": "minecraft:gray_shulker_box",
  "Gray Stained Glass": "minecraft:gray_stained_glass",
  "Gray Stained Glass Pane": "minecraft:gray_stained_glass_pane",
  "Gray Terracotta": "minecraft:gray_terracotta",
  "Gray Wool": "minecraft:gray_wool",
  "Green Banner": "minecraft:green_banner",
  "Green Bed": "minecraft:green_bed",
  "Green Candle": "minecraft:green_candle",
  "Cake with Green Candle": "minecraft:green_candle_cake",
  "Green Carpet": "minecraft:green_carpet",
  "Green Concrete": "minecraft:green_concrete",
  "Green Concrete Powder": "minecraft:green_concrete_powder",
  "Green Glazed Terracotta": "minecraft:green_glazed_terracotta",
  "Green Shulker Box": "minecraft:green_shulker_box",
  "Green Stained Glass": "minecraft:green_stained_glass",
  "Green Stained Glass Pane": "minecraft:green_stained_glass_pane",
  "Green Terracotta": "minecraft:green_terracotta",
  "Green Wool": "minecraft:green_wool",
  Grindstone: "minecraft:grindstone",
  "Hanging Roots": "minecraft:hanging_roots",
  "Hay Bale": "minecraft:hay_block",
  "Heavy Weighted Pressure Plate": "minecraft:heavy_weighted_pressure_plate",
  "Honey Block": "minecraft:honey_block",
  "Honeycomb Block": "minecraft:honeycomb_block",
  Hopper: "minecraft:hopper",
  "Horn Coral": "minecraft:horn_coral",
  "Horn Coral Block": "minecraft:horn_coral_block",
  "Horn Coral Fan": "minecraft:horn_coral_fan",
  "Horn Coral Wall Fan": "minecraft:horn_coral_wall_fan",
  Ice: "minecraft:ice",
  "Infested Chiseled Stone Bricks": "minecraft:infested_chiseled_stone_bricks",
  "Infested Cobblestone": "minecraft:infested_cobblestone",
  "Infested Cracked Stone Bricks": "minecraft:infested_cracked_stone_bricks",
  "Infested Deepslate": "minecraft:infested_deepslate",
  "Infested Mossy Stone Bricks": "minecraft:infested_mossy_stone_bricks",
  "Infested Stone": "minecraft:infested_stone",
  "Infested Stone Bricks": "minecraft:infested_stone_bricks",
  "Iron Bars": "minecraft:iron_bars",
  "Block of Iron": "minecraft:iron_block",
  "Iron Door": "minecraft:iron_door",
  "Iron Ore": "minecraft:iron_ore",
  "Iron Trapdoor": "minecraft:iron_trapdoor",
  "Jack o'Lantern": "minecraft:jack_o_lantern",
  "Jigsaw Block": "minecraft:jigsaw",
  Jukebox: "minecraft:jukebox",
  "Jungle Button": "minecraft:jungle_button",
  "Jungle Door": "minecraft:jungle_door",
  "Jungle Fence": "minecraft:jungle_fence",
  "Jungle Fence Gate": "minecraft:jungle_fence_gate",
  "Jungle Hanging Sign": "minecraft:jungle_hanging_sign",
  "Jungle Leaves": "minecraft:jungle_leaves",
  "Jungle Log": "minecraft:jungle_log",
  "Jungle Planks": "minecraft:jungle_planks",
  "Jungle Pressure Plate": "minecraft:jungle_pressure_plate",
  "Jungle Sapling": "minecraft:jungle_sapling",
  "Jungle Sign": "minecraft:jungle_sign",
  "Jungle Slab": "minecraft:jungle_slab",
  "Jungle Stairs": "minecraft:jungle_stairs",
  "Jungle Trapdoor": "minecraft:jungle_trapdoor",
  "Jungle Wall Hanging Sign": "minecraft:jungle_wall_hanging_sign",
  "Jungle Wall Sign": "minecraft:jungle_wall_sign",
  "Jungle Wood": "minecraft:jungle_wood",
  Kelp: "minecraft:kelp",
  "Kelp Plant": "minecraft:kelp_plant",
  Ladder: "minecraft:ladder",
  Lantern: "minecraft:lantern",
  "Block of Lapis Lazuli": "minecraft:lapis_block",
  "Lapis Lazuli Ore": "minecraft:lapis_ore",
  "Large Amethyst Bud": "minecraft:large_amethyst_bud",
  "Large Fern": "minecraft:large_fern",
  Lava: "minecraft:lava",
  "Lava Cauldron": "minecraft:lava_cauldron",
  Lectern: "minecraft:lectern",
  Lever: "minecraft:lever",
  Light: "minecraft:light",
  "Light Blue Banner": "minecraft:light_blue_banner",
  "Light Blue Bed": "minecraft:light_blue_bed",
  "Light Blue Candle": "minecraft:light_blue_candle",
  "Cake with Light Blue Candle": "minecraft:light_blue_candle_cake",
  "Light Blue Carpet": "minecraft:light_blue_carpet",
  "Light Blue Concrete": "minecraft:light_blue_concrete",
  "Light Blue Concrete Powder": "minecraft:light_blue_concrete_powder",
  "Light Blue Glazed Terracotta": "minecraft:light_blue_glazed_terracotta",
  "Light Blue Shulker Box": "minecraft:light_blue_shulker_box",
  "Light Blue Stained Glass": "minecraft:light_blue_stained_glass",
  "Light Blue Stained Glass Pane": "minecraft:light_blue_stained_glass_pane",
  "Light Blue Terracotta": "minecraft:light_blue_terracotta",
  "Light Blue Wool": "minecraft:light_blue_wool",
  "Light Gray Banner": "minecraft:light_gray_banner",
  "Light Gray Bed": "minecraft:light_gray_bed",
  "Light Gray Candle": "minecraft:light_gray_candle",
  "Cake with Light Gray Candle": "minecraft:light_gray_candle_cake",
  "Light Gray Carpet": "minecraft:light_gray_carpet",
  "Light Gray Concrete": "minecraft:light_gray_concrete",
  "Light Gray Concrete Powder": "minecraft:light_gray_concrete_powder",
  "Light Gray Glazed Terracotta": "minecraft:light_gray_glazed_terracotta",
  "Light Gray Shulker Box": "minecraft:light_gray_shulker_box",
  "Light Gray Stained Glass": "minecraft:light_gray_stained_glass",
  "Light Gray Stained Glass Pane": "minecraft:light_gray_stained_glass_pane",
  "Light Gray Terracotta": "minecraft:light_gray_terracotta",
  "Light Gray Wool": "minecraft:light_gray_wool",
  "Light Weighted Pressure Plate": "minecraft:light_weighted_pressure_plate",
  "Lightning Rod": "minecraft:lightning_rod",
  Lilac: "minecraft:lilac",
  "Lily of the Valley": "minecraft:lily_of_the_valley",
  "Lily Pad": "minecraft:lily_pad",
  "Lime Banner": "minecraft:lime_banner",
  "Lime Bed": "minecraft:lime_bed",
  "Lime Candle": "minecraft:lime_candle",
  "Cake with Lime Candle": "minecraft:lime_candle_cake",
  "Lime Carpet": "minecraft:lime_carpet",
  "Lime Concrete": "minecraft:lime_concrete",
  "Lime Concrete Powder": "minecraft:lime_concrete_powder",
  "Lime Glazed Terracotta": "minecraft:lime_glazed_terracotta",
  "Lime Shulker Box": "minecraft:lime_shulker_box",
  "Lime Stained Glass": "minecraft:lime_stained_glass",
  "Lime Stained Glass Pane": "minecraft:lime_stained_glass_pane",
  "Lime Terracotta": "minecraft:lime_terracotta",
  "Lime Wool": "minecraft:lime_wool",
  Lodestone: "minecraft:lodestone",
  Loom: "minecraft:loom",
  "Magenta Banner": "minecraft:magenta_banner",
  "Magenta Bed": "minecraft:magenta_bed",
  "Magenta Candle": "minecraft:magenta_candle",
  "Cake with Magenta Candle": "minecraft:magenta_candle_cake",
  "Magenta Carpet": "minecraft:magenta_carpet",
  "Magenta Concrete": "minecraft:magenta_concrete",
  "Magenta Concrete Powder": "minecraft:magenta_concrete_powder",
  "Magenta Glazed Terracotta": "minecraft:magenta_glazed_terracotta",
  "Magenta Shulker Box": "minecraft:magenta_shulker_box",
  "Magenta Stained Glass": "minecraft:magenta_stained_glass",
  "Magenta Stained Glass Pane": "minecraft:magenta_stained_glass_pane",
  "Magenta Terracotta": "minecraft:magenta_terracotta",
  "Magenta Wool": "minecraft:magenta_wool",
  "Magma Block": "minecraft:magma_block",
  "Mangrove Button": "minecraft:mangrove_button",
  "Mangrove Door": "minecraft:mangrove_door",
  "Mangrove Fence": "minecraft:mangrove_fence",
  "Mangrove Fence Gate": "minecraft:mangrove_fence_gate",
  "Mangrove Hanging Sign": "minecraft:mangrove_hanging_sign",
  "Mangrove Leaves": "minecraft:mangrove_leaves",
  "Mangrove Log": "minecraft:mangrove_log",
  "Mangrove Planks": "minecraft:mangrove_planks",
  "Mangrove Pressure Plate": "minecraft:mangrove_pressure_plate",
  "Mangrove Propagule": "minecraft:mangrove_propagule",
  "Mangrove Roots": "minecraft:mangrove_roots",
  "Mangrove Sign": "minecraft:mangrove_sign",
  "Mangrove Slab": "minecraft:mangrove_slab",
  "Mangrove Stairs": "minecraft:mangrove_stairs",
  "Mangrove Trapdoor": "minecraft:mangrove_trapdoor",
  "Mangrove Wall Hanging Sign": "minecraft:mangrove_wall_hanging_sign",
  "Mangrove Wall Sign": "minecraft:mangrove_wall_sign",
  "Mangrove Wood": "minecraft:mangrove_wood",
  "Medium Amethyst Bud": "minecraft:medium_amethyst_bud",
  Melon: "minecraft:melon",
  "Melon Stem": "minecraft:melon_stem",
  "Moss Block": "minecraft:moss_block",
  "Moss Carpet": "minecraft:moss_carpet",
  "Mossy Cobblestone": "minecraft:mossy_cobblestone",
  "Mossy Cobblestone Slab": "minecraft:mossy_cobblestone_slab",
  "Mossy Cobblestone Stairs": "minecraft:mossy_cobblestone_stairs",
  "Mossy Cobblestone Wall": "minecraft:mossy_cobblestone_wall",
  "Mossy Stone Brick Slab": "minecraft:mossy_stone_brick_slab",
  "Mossy Stone Brick Stairs": "minecraft:mossy_stone_brick_stairs",
  "Mossy Stone Brick Wall": "minecraft:mossy_stone_brick_wall",
  "Mossy Stone Bricks": "minecraft:mossy_stone_bricks",
  "Moving Piston": "minecraft:moving_piston",
  Mud: "minecraft:mud",
  "Mud Brick Slab": "minecraft:mud_brick_slab",
  "Mud Brick Stairs": "minecraft:mud_brick_stairs",
  "Mud Brick Wall": "minecraft:mud_brick_wall",
  "Mud Bricks": "minecraft:mud_bricks",
  "Muddy Mangrove Roots": "minecraft:muddy_mangrove_roots",
  "Mushroom Stem": "minecraft:mushroom_stem",
  Mycelium: "minecraft:mycelium",
  "Nether Brick Fence": "minecraft:nether_brick_fence",
  "Nether Brick Slab": "minecraft:nether_brick_slab",
  "Nether Brick Stairs": "minecraft:nether_brick_stairs",
  "Nether Brick Wall": "minecraft:nether_brick_wall",
  "Nether Bricks": "minecraft:nether_bricks",
  "Nether Gold Ore": "minecraft:nether_gold_ore",
  "Nether Portal": "minecraft:nether_portal",
  "Nether Quartz Ore": "minecraft:nether_quartz_ore",
  "Nether Sprouts": "minecraft:nether_sprouts",
  "Nether Wart": "minecraft:nether_wart",
  "Nether Wart Block": "minecraft:nether_wart_block",
  "Block of Netherite": "minecraft:netherite_block",
  Netherrack: "minecraft:netherrack",
  "Note Block": "minecraft:note_block",
  "Oak Button": "minecraft:oak_button",
  "Oak Door": "minecraft:oak_door",
  "Oak Fence": "minecraft:oak_fence",
  "Oak Fence Gate": "minecraft:oak_fence_gate",
  "Oak Hanging Sign": "minecraft:oak_hanging_sign",
  "Oak Leaves": "minecraft:oak_leaves",
  "Oak Log": "minecraft:oak_log",
  "Oak Planks": "minecraft:oak_planks",
  "Oak Pressure Plate": "minecraft:oak_pressure_plate",
  "Oak Sapling": "minecraft:oak_sapling",
  "Oak Sign": "minecraft:oak_sign",
  "Oak Slab": "minecraft:oak_slab",
  "Oak Stairs": "minecraft:oak_stairs",
  "Oak Trapdoor": "minecraft:oak_trapdoor",
  "Oak Wall Hanging Sign": "minecraft:oak_wall_hanging_sign",
  "Oak Wall Sign": "minecraft:oak_wall_sign",
  "Oak Wood": "minecraft:oak_wood",
  Observer: "minecraft:observer",
  Obsidian: "minecraft:obsidian",
  "Ochre Froglight": "minecraft:ochre_froglight",
  "Ominous Banner": "minecraft:ominous_banner",
  "Orange Banner": "minecraft:orange_banner",
  "Orange Bed": "minecraft:orange_bed",
  "Orange Candle": "minecraft:orange_candle",
  "Cake with Orange Candle": "minecraft:orange_candle_cake",
  "Orange Carpet": "minecraft:orange_carpet",
  "Orange Concrete": "minecraft:orange_concrete",
  "Orange Concrete Powder": "minecraft:orange_concrete_powder",
  "Orange Glazed Terracotta": "minecraft:orange_glazed_terracotta",
  "Orange Shulker Box": "minecraft:orange_shulker_box",
  "Orange Stained Glass": "minecraft:orange_stained_glass",
  "Orange Stained Glass Pane": "minecraft:orange_stained_glass_pane",
  "Orange Terracotta": "minecraft:orange_terracotta",
  "Orange Tulip": "minecraft:orange_tulip",
  "Orange Wool": "minecraft:orange_wool",
  "Oxeye Daisy": "minecraft:oxeye_daisy",
  "Oxidized Copper": "minecraft:oxidized_copper",
  "Oxidized Cut Copper": "minecraft:oxidized_cut_copper",
  "Oxidized Cut Copper Slab": "minecraft:oxidized_cut_copper_slab",
  "Oxidized Cut Copper Stairs": "minecraft:oxidized_cut_copper_stairs",
  "Packed Ice": "minecraft:packed_ice",
  "Packed Mud": "minecraft:packed_mud",
  "Pearlescent Froglight": "minecraft:pearlescent_froglight",
  Peony: "minecraft:peony",
  "Petrified Oak Slab": "minecraft:petrified_oak_slab",
  "Piglin Head": "minecraft:piglin_head",
  "Piglin Wall Head": "minecraft:piglin_wall_head",
  "Pink Banner": "minecraft:pink_banner",
  "Pink Bed": "minecraft:pink_bed",
  "Pink Candle": "minecraft:pink_candle",
  "Cake with Pink Candle": "minecraft:pink_candle_cake",
  "Pink Carpet": "minecraft:pink_carpet",
  "Pink Concrete": "minecraft:pink_concrete",
  "Pink Concrete Powder": "minecraft:pink_concrete_powder",
  "Pink Glazed Terracotta": "minecraft:pink_glazed_terracotta",
  "Pink Petals": "minecraft:pink_petals",
  "Pink Shulker Box": "minecraft:pink_shulker_box",
  "Pink Stained Glass": "minecraft:pink_stained_glass",
  "Pink Stained Glass Pane": "minecraft:pink_stained_glass_pane",
  "Pink Terracotta": "minecraft:pink_terracotta",
  "Pink Tulip": "minecraft:pink_tulip",
  "Pink Wool": "minecraft:pink_wool",
  Piston: "minecraft:piston",
  "Piston Head": "minecraft:piston_head",
  "Pitcher Crop": "minecraft:pitcher_crop",
  "Pitcher Plant": "minecraft:pitcher_plant",
  "Player Head": "minecraft:player_head",
  "Player Wall Head": "minecraft:player_wall_head",
  Podzol: "minecraft:podzol",
  "Pointed Dripstone": "minecraft:pointed_dripstone",
  "Polished Andesite": "minecraft:polished_andesite",
  "Polished Andesite Slab": "minecraft:polished_andesite_slab",
  "Polished Andesite Stairs": "minecraft:polished_andesite_stairs",
  "Polished Basalt": "minecraft:polished_basalt",
  "Polished Blackstone": "minecraft:polished_blackstone",
  "Polished Blackstone Brick Slab": "minecraft:polished_blackstone_brick_slab",
  "Polished Blackstone Brick Stairs":
    "minecraft:polished_blackstone_brick_stairs",
  "Polished Blackstone Brick Wall": "minecraft:polished_blackstone_brick_wall",
  "Polished Blackstone Bricks": "minecraft:polished_blackstone_bricks",
  "Polished Blackstone Button": "minecraft:polished_blackstone_button",
  "Polished Blackstone Pressure Plate":
    "minecraft:polished_blackstone_pressure_plate",
  "Polished Blackstone Slab": "minecraft:polished_blackstone_slab",
  "Polished Blackstone Stairs": "minecraft:polished_blackstone_stairs",
  "Polished Blackstone Wall": "minecraft:polished_blackstone_wall",
  "Polished Deepslate": "minecraft:polished_deepslate",
  "Polished Deepslate Slab": "minecraft:polished_deepslate_slab",
  "Polished Deepslate Stairs": "minecraft:polished_deepslate_stairs",
  "Polished Deepslate Wall": "minecraft:polished_deepslate_wall",
  "Polished Diorite": "minecraft:polished_diorite",
  "Polished Diorite Slab": "minecraft:polished_diorite_slab",
  "Polished Diorite Stairs": "minecraft:polished_diorite_stairs",
  "Polished Granite": "minecraft:polished_granite",
  "Polished Granite Slab": "minecraft:polished_granite_slab",
  "Polished Granite Stairs": "minecraft:polished_granite_stairs",
  Poppy: "minecraft:poppy",
  Potatoes: "minecraft:potatoes",
  "Potted Acacia Sapling": "minecraft:potted_acacia_sapling",
  "Potted Allium": "minecraft:potted_allium",
  "Potted Azalea": "minecraft:potted_azalea_bush",
  "Potted Azure Bluet": "minecraft:potted_azure_bluet",
  "Potted Bamboo": "minecraft:potted_bamboo",
  "Potted Birch Sapling": "minecraft:potted_birch_sapling",
  "Potted Blue Orchid": "minecraft:potted_blue_orchid",
  "Potted Brown Mushroom": "minecraft:potted_brown_mushroom",
  "Potted Cactus": "minecraft:potted_cactus",
  "Potted Cherry Sapling": "minecraft:potted_cherry_sapling",
  "Potted Cornflower": "minecraft:potted_cornflower",
  "Potted Crimson Fungus": "minecraft:potted_crimson_fungus",
  "Potted Crimson Roots": "minecraft:potted_crimson_roots",
  "Potted Dandelion": "minecraft:potted_dandelion",
  "Potted Dark Oak Sapling": "minecraft:potted_dark_oak_sapling",
  "Potted Dead Bush": "minecraft:potted_dead_bush",
  "Potted Fern": "minecraft:potted_fern",
  "Potted Flowering Azalea": "minecraft:potted_flowering_azalea_bush",
  "Potted Jungle Sapling": "minecraft:potted_jungle_sapling",
  "Potted Lily of the Valley": "minecraft:potted_lily_of_the_valley",
  "Potted Mangrove Propagule": "minecraft:potted_mangrove_propagule",
  "Potted Oak Sapling": "minecraft:potted_oak_sapling",
  "Potted Orange Tulip": "minecraft:potted_orange_tulip",
  "Potted Oxeye Daisy": "minecraft:potted_oxeye_daisy",
  "Potted Pink Tulip": "minecraft:potted_pink_tulip",
  "Potted Poppy": "minecraft:potted_poppy",
  "Potted Red Mushroom": "minecraft:potted_red_mushroom",
  "Potted Red Tulip": "minecraft:potted_red_tulip",
  "Potted Spruce Sapling": "minecraft:potted_spruce_sapling",
  "Potted Torchflower": "minecraft:potted_torchflower",
  "Potted Warped Fungus": "minecraft:potted_warped_fungus",
  "Potted Warped Roots": "minecraft:potted_warped_roots",
  "Potted White Tulip": "minecraft:potted_white_tulip",
  "Potted Wither Rose": "minecraft:potted_wither_rose",
  "Powder Snow": "minecraft:powder_snow",
  "Powder Snow Cauldron": "minecraft:powder_snow_cauldron",
  "Powered Rail": "minecraft:powered_rail",
  Prismarine: "minecraft:prismarine",
  "Prismarine Brick Slab": "minecraft:prismarine_brick_slab",
  "Prismarine Brick Stairs": "minecraft:prismarine_brick_stairs",
  "Prismarine Bricks": "minecraft:prismarine_bricks",
  "Prismarine Slab": "minecraft:prismarine_slab",
  "Prismarine Stairs": "minecraft:prismarine_stairs",
  "Prismarine Wall": "minecraft:prismarine_wall",
  Pumpkin: "minecraft:pumpkin",
  "Pumpkin Stem": "minecraft:pumpkin_stem",
  "Purple Banner": "minecraft:purple_banner",
  "Purple Bed": "minecraft:purple_bed",
  "Purple Candle": "minecraft:purple_candle",
  "Cake with Purple Candle": "minecraft:purple_candle_cake",
  "Purple Carpet": "minecraft:purple_carpet",
  "Purple Concrete": "minecraft:purple_concrete",
  "Purple Concrete Powder": "minecraft:purple_concrete_powder",
  "Purple Glazed Terracotta": "minecraft:purple_glazed_terracotta",
  "Purple Shulker Box": "minecraft:purple_shulker_box",
  "Purple Stained Glass": "minecraft:purple_stained_glass",
  "Purple Stained Glass Pane": "minecraft:purple_stained_glass_pane",
  "Purple Terracotta": "minecraft:purple_terracotta",
  "Purple Wool": "minecraft:purple_wool",
  "Purpur Block": "minecraft:purpur_block",
  "Purpur Pillar": "minecraft:purpur_pillar",
  "Purpur Slab": "minecraft:purpur_slab",
  "Purpur Stairs": "minecraft:purpur_stairs",
  "Block of Quartz": "minecraft:quartz_block",
  "Quartz Bricks": "minecraft:quartz_bricks",
  "Quartz Pillar": "minecraft:quartz_pillar",
  "Quartz Slab": "minecraft:quartz_slab",
  "Quartz Stairs": "minecraft:quartz_stairs",
  Rail: "minecraft:rail",
  "Block of Raw Copper": "minecraft:raw_copper_block",
  "Block of Raw Gold": "minecraft:raw_gold_block",
  "Block of Raw Iron": "minecraft:raw_iron_block",
  "Red Banner": "minecraft:red_banner",
  Bed: "minecraft:red_bed",
  "Red Bed": "minecraft:red_bed",
  "Red Candle": "minecraft:red_candle",
  "Cake with Red Candle": "minecraft:red_candle_cake",
  "Red Carpet": "minecraft:red_carpet",
  "Red Concrete": "minecraft:red_concrete",
  "Red Concrete Powder": "minecraft:red_concrete_powder",
  "Red Glazed Terracotta": "minecraft:red_glazed_terracotta",
  "Red Mushroom": "minecraft:red_mushroom",
  "Red Mushroom Block": "minecraft:red_mushroom_block",
  "Red Nether Brick Slab": "minecraft:red_nether_brick_slab",
  "Red Nether Brick Stairs": "minecraft:red_nether_brick_stairs",
  "Red Nether Brick Wall": "minecraft:red_nether_brick_wall",
  "Red Nether Bricks": "minecraft:red_nether_bricks",
  "Red Sand": "minecraft:red_sand",
  "Red Sandstone": "minecraft:red_sandstone",
  "Red Sandstone Slab": "minecraft:red_sandstone_slab",
  "Red Sandstone Stairs": "minecraft:red_sandstone_stairs",
  "Red Sandstone Wall": "minecraft:red_sandstone_wall",
  "Red Shulker Box": "minecraft:red_shulker_box",
  "Red Stained Glass": "minecraft:red_stained_glass",
  "Red Stained Glass Pane": "minecraft:red_stained_glass_pane",
  "Red Terracotta": "minecraft:red_terracotta",
  "Red Tulip": "minecraft:red_tulip",
  "Red Wool": "minecraft:red_wool",
  "Block of Redstone": "minecraft:redstone_block",
  "Redstone Lamp": "minecraft:redstone_lamp",
  "Redstone Ore": "minecraft:redstone_ore",
  "Redstone Torch": "minecraft:redstone_torch",
  "Redstone Wall Torch": "minecraft:redstone_wall_torch",
  "Redstone Wire": "minecraft:redstone_wire",
  "Reinforced Deepslate": "minecraft:reinforced_deepslate",
  "Redstone Repeater": "minecraft:repeater",
  "Repeating Command Block": "minecraft:repeating_command_block",
  "Respawn Anchor": "minecraft:respawn_anchor",
  "Rooted Dirt": "minecraft:rooted_dirt",
  "Rose Bush": "minecraft:rose_bush",
  Sand: "minecraft:sand",
  Sandstone: "minecraft:sandstone",
  "Sandstone Slab": "minecraft:sandstone_slab",
  "Sandstone Stairs": "minecraft:sandstone_stairs",
  "Sandstone Wall": "minecraft:sandstone_wall",
  Scaffolding: "minecraft:scaffolding",
  Sculk: "minecraft:sculk",
  "Sculk Catalyst": "minecraft:sculk_catalyst",
  "Sculk Sensor": "minecraft:sculk_sensor",
  "Sculk Shrieker": "minecraft:sculk_shrieker",
  "Sculk Vein": "minecraft:sculk_vein",
  "Sea Lantern": "minecraft:sea_lantern",
  "Sea Pickle": "minecraft:sea_pickle",
  Seagrass: "minecraft:seagrass",
  "Respawn point set": "minecraft:set_spawn",
  Shroomlight: "minecraft:shroomlight",
  "Shulker Box": "minecraft:shulker_box",
  "Skeleton Skull": "minecraft:skeleton_skull",
  "Skeleton Wall Skull": "minecraft:skeleton_wall_skull",
  "Slime Block": "minecraft:slime_block",
  "Small Amethyst Bud": "minecraft:small_amethyst_bud",
  "Small Dripleaf": "minecraft:small_dripleaf",
  "Smithing Table": "minecraft:smithing_table",
  Smoker: "minecraft:smoker",
  "Smooth Basalt": "minecraft:smooth_basalt",
  "Smooth Quartz Block": "minecraft:smooth_quartz",
  "Smooth Quartz Slab": "minecraft:smooth_quartz_slab",
  "Smooth Quartz Stairs": "minecraft:smooth_quartz_stairs",
  "Smooth Red Sandstone": "minecraft:smooth_red_sandstone",
  "Smooth Red Sandstone Slab": "minecraft:smooth_red_sandstone_slab",
  "Smooth Red Sandstone Stairs": "minecraft:smooth_red_sandstone_stairs",
  "Smooth Sandstone": "minecraft:smooth_sandstone",
  "Smooth Sandstone Slab": "minecraft:smooth_sandstone_slab",
  "Smooth Sandstone Stairs": "minecraft:smooth_sandstone_stairs",
  "Smooth Stone": "minecraft:smooth_stone",
  "Smooth Stone Slab": "minecraft:smooth_stone_slab",
  "Sniffer Egg": "minecraft:sniffer_egg",
  Snow: "minecraft:snow",
  "Snow Block": "minecraft:snow_block",
  "Soul Campfire": "minecraft:soul_campfire",
  "Soul Fire": "minecraft:soul_fire",
  "Soul Lantern": "minecraft:soul_lantern",
  "Soul Sand": "minecraft:soul_sand",
  "Soul Soil": "minecraft:soul_soil",
  "Soul Torch": "minecraft:soul_torch",
  "Soul Wall Torch": "minecraft:soul_wall_torch",
  "Monster Spawner": "minecraft:spawner",
  Sponge: "minecraft:sponge",
  "Spore Blossom": "minecraft:spore_blossom",
  "Spruce Button": "minecraft:spruce_button",
  "Spruce Door": "minecraft:spruce_door",
  "Spruce Fence": "minecraft:spruce_fence",
  "Spruce Fence Gate": "minecraft:spruce_fence_gate",
  "Spruce Hanging Sign": "minecraft:spruce_hanging_sign",
  "Spruce Leaves": "minecraft:spruce_leaves",
  "Spruce Log": "minecraft:spruce_log",
  "Spruce Planks": "minecraft:spruce_planks",
  "Spruce Pressure Plate": "minecraft:spruce_pressure_plate",
  "Spruce Sapling": "minecraft:spruce_sapling",
  "Spruce Sign": "minecraft:spruce_sign",
  "Spruce Slab": "minecraft:spruce_slab",
  "Spruce Stairs": "minecraft:spruce_stairs",
  "Spruce Trapdoor": "minecraft:spruce_trapdoor",
  "Spruce Wall Hanging Sign": "minecraft:spruce_wall_hanging_sign",
  "Spruce Wall Sign": "minecraft:spruce_wall_sign",
  "Spruce Wood": "minecraft:spruce_wood",
  "Sticky Piston": "minecraft:sticky_piston",
  Stone: "minecraft:stone",
  "Stone Brick Slab": "minecraft:stone_brick_slab",
  "Stone Brick Stairs": "minecraft:stone_brick_stairs",
  "Stone Brick Wall": "minecraft:stone_brick_wall",
  "Stone Bricks": "minecraft:stone_bricks",
  "Stone Button": "minecraft:stone_button",
  "Stone Pressure Plate": "minecraft:stone_pressure_plate",
  "Stone Slab": "minecraft:stone_slab",
  "Stone Stairs": "minecraft:stone_stairs",
  Stonecutter: "minecraft:stonecutter",
  "Stripped Acacia Log": "minecraft:stripped_acacia_log",
  "Stripped Acacia Wood": "minecraft:stripped_acacia_wood",
  "Block of Stripped Bamboo": "minecraft:stripped_bamboo_block",
  "Stripped Birch Log": "minecraft:stripped_birch_log",
  "Stripped Birch Wood": "minecraft:stripped_birch_wood",
  "Stripped Cherry Log": "minecraft:stripped_cherry_log",
  "Stripped Cherry Wood": "minecraft:stripped_cherry_wood",
  "Stripped Crimson Hyphae": "minecraft:stripped_crimson_hyphae",
  "Stripped Crimson Stem": "minecraft:stripped_crimson_stem",
  "Stripped Dark Oak Log": "minecraft:stripped_dark_oak_log",
  "Stripped Dark Oak Wood": "minecraft:stripped_dark_oak_wood",
  "Stripped Jungle Log": "minecraft:stripped_jungle_log",
  "Stripped Jungle Wood": "minecraft:stripped_jungle_wood",
  "Stripped Mangrove Log": "minecraft:stripped_mangrove_log",
  "Stripped Mangrove Wood": "minecraft:stripped_mangrove_wood",
  "Stripped Oak Log": "minecraft:stripped_oak_log",
  "Stripped Oak Wood": "minecraft:stripped_oak_wood",
  "Stripped Spruce Log": "minecraft:stripped_spruce_log",
  "Stripped Spruce Wood": "minecraft:stripped_spruce_wood",
  "Stripped Warped Hyphae": "minecraft:stripped_warped_hyphae",
  "Stripped Warped Stem": "minecraft:stripped_warped_stem",
  "Structure Block": "minecraft:structure_block",
  "Structure Void": "minecraft:structure_void",
  "Sugar Cane": "minecraft:sugar_cane",
  Sunflower: "minecraft:sunflower",
  "Suspicious Gravel": "minecraft:suspicious_gravel",
  "Suspicious Sand": "minecraft:suspicious_sand",
  "Sweet Berry Bush": "minecraft:sweet_berry_bush",
  "Tall Grass": "minecraft:tall_grass",
  "Tall Seagrass": "minecraft:tall_seagrass",
  Target: "minecraft:target",
  Terracotta: "minecraft:terracotta",
  "Tinted Glass": "minecraft:tinted_glass",
  TNT: "minecraft:tnt",
  Torch: "minecraft:torch",
  Torchflower: "minecraft:torchflower",
  "Torchflower Crop": "minecraft:torchflower_crop",
  "Trapped Chest": "minecraft:trapped_chest",
  Tripwire: "minecraft:tripwire",
  "Tripwire Hook": "minecraft:tripwire_hook",
  "Tube Coral": "minecraft:tube_coral",
  "Tube Coral Block": "minecraft:tube_coral_block",
  "Tube Coral Fan": "minecraft:tube_coral_fan",
  "Tube Coral Wall Fan": "minecraft:tube_coral_wall_fan",
  Tuff: "minecraft:tuff",
  "Turtle Egg": "minecraft:turtle_egg",
  "Twisting Vines": "minecraft:twisting_vines",
  "Twisting Vines Plant": "minecraft:twisting_vines_plant",
  "Verdant Froglight": "minecraft:verdant_froglight",
  Vines: "minecraft:vine",
  "Void Air": "minecraft:void_air",
  "Wall Torch": "minecraft:wall_torch",
  "Warped Button": "minecraft:warped_button",
  "Warped Door": "minecraft:warped_door",
  "Warped Fence": "minecraft:warped_fence",
  "Warped Fence Gate": "minecraft:warped_fence_gate",
  "Warped Fungus": "minecraft:warped_fungus",
  "Warped Hanging Sign": "minecraft:warped_hanging_sign",
  "Warped Hyphae": "minecraft:warped_hyphae",
  "Warped Nylium": "minecraft:warped_nylium",
  "Warped Planks": "minecraft:warped_planks",
  "Warped Pressure Plate": "minecraft:warped_pressure_plate",
  "Warped Roots": "minecraft:warped_roots",
  "Warped Sign": "minecraft:warped_sign",
  "Warped Slab": "minecraft:warped_slab",
  "Warped Stairs": "minecraft:warped_stairs",
  "Warped Stem": "minecraft:warped_stem",
  "Warped Trapdoor": "minecraft:warped_trapdoor",
  "Warped Wall Hanging Sign": "minecraft:warped_wall_hanging_sign",
  "Warped Wall Sign": "minecraft:warped_wall_sign",
  "Warped Wart Block": "minecraft:warped_wart_block",
  Water: "minecraft:water",
  "Water Cauldron": "minecraft:water_cauldron",
  "Waxed Block of Copper": "minecraft:waxed_copper_block",
  "Waxed Cut Copper": "minecraft:waxed_cut_copper",
  "Waxed Cut Copper Slab": "minecraft:waxed_cut_copper_slab",
  "Waxed Cut Copper Stairs": "minecraft:waxed_cut_copper_stairs",
  "Waxed Exposed Copper": "minecraft:waxed_exposed_copper",
  "Waxed Exposed Cut Copper": "minecraft:waxed_exposed_cut_copper",
  "Waxed Exposed Cut Copper Slab": "minecraft:waxed_exposed_cut_copper_slab",
  "Waxed Exposed Cut Copper Stairs":
    "minecraft:waxed_exposed_cut_copper_stairs",
  "Waxed Oxidized Copper": "minecraft:waxed_oxidized_copper",
  "Waxed Oxidized Cut Copper": "minecraft:waxed_oxidized_cut_copper",
  "Waxed Oxidized Cut Copper Slab": "minecraft:waxed_oxidized_cut_copper_slab",
  "Waxed Oxidized Cut Copper Stairs":
    "minecraft:waxed_oxidized_cut_copper_stairs",
  "Waxed Weathered Copper": "minecraft:waxed_weathered_copper",
  "Waxed Weathered Cut Copper": "minecraft:waxed_weathered_cut_copper",
  "Waxed Weathered Cut Copper Slab":
    "minecraft:waxed_weathered_cut_copper_slab",
  "Waxed Weathered Cut Copper Stairs":
    "minecraft:waxed_weathered_cut_copper_stairs",
  "Weathered Copper": "minecraft:weathered_copper",
  "Weathered Cut Copper": "minecraft:weathered_cut_copper",
  "Weathered Cut Copper Slab": "minecraft:weathered_cut_copper_slab",
  "Weathered Cut Copper Stairs": "minecraft:weathered_cut_copper_stairs",
  "Weeping Vines": "minecraft:weeping_vines",
  "Weeping Vines Plant": "minecraft:weeping_vines_plant",
  "Wet Sponge": "minecraft:wet_sponge",
  "Wheat Crops": "minecraft:wheat",
  "White Banner": "minecraft:white_banner",
  "White Bed": "minecraft:white_bed",
  "White Candle": "minecraft:white_candle",
  "Cake with White Candle": "minecraft:white_candle_cake",
  "White Carpet": "minecraft:white_carpet",
  "White Concrete": "minecraft:white_concrete",
  "White Concrete Powder": "minecraft:white_concrete_powder",
  "White Glazed Terracotta": "minecraft:white_glazed_terracotta",
  "White Shulker Box": "minecraft:white_shulker_box",
  "White Stained Glass": "minecraft:white_stained_glass",
  "White Stained Glass Pane": "minecraft:white_stained_glass_pane",
  "White Terracotta": "minecraft:white_terracotta",
  "White Tulip": "minecraft:white_tulip",
  "White Wool": "minecraft:white_wool",
  "Wither Rose": "minecraft:wither_rose",
  "Wither Skeleton Skull": "minecraft:wither_skeleton_skull",
  "Wither Skeleton Wall Skull": "minecraft:wither_skeleton_wall_skull",
  "Yellow Banner": "minecraft:yellow_banner",
  "Yellow Bed": "minecraft:yellow_bed",
  "Yellow Candle": "minecraft:yellow_candle",
  "Cake with Yellow Candle": "minecraft:yellow_candle_cake",
  "Yellow Carpet": "minecraft:yellow_carpet",
  "Yellow Concrete": "minecraft:yellow_concrete",
  "Yellow Concrete Powder": "minecraft:yellow_concrete_powder",
  "Yellow Glazed Terracotta": "minecraft:yellow_glazed_terracotta",
  "Yellow Shulker Box": "minecraft:yellow_shulker_box",
  "Yellow Stained Glass": "minecraft:yellow_stained_glass",
  "Yellow Stained Glass Pane": "minecraft:yellow_stained_glass_pane",
  "Yellow Terracotta": "minecraft:yellow_terracotta",
  "Yellow Wool": "minecraft:yellow_wool",
  "Zombie Head": "minecraft:zombie_head",
  "Zombie Wall Head": "minecraft:zombie_wall_head",
};
